main: "com.cutesmouse.therichman.Main"
version: 1.0
author: "CutesMouse"
name: "TheRichMan"
api-version: "1.20"
description: "A game that has been redesigned to plugin"
depend:
  - WorldEdit
commands:
  start:
    description: "start"
    usage: "start"